AuthFsHostTest: Ignore output dir already created
Address a test failure where the setup phase of the test tries to mkdir
the output directory and fails as it already exists (probably due to
another test having created it):

    java.lang.AssertionError: mkdir /data/local/tmp/authfs/output_dir/dir has failed:
        CommandResult: exit code=1, out=, err=mkdir: '/data/local/tmp/authfs/output_dir/dir': File exists

    at org.junit.Assert.fail(Assert.java:89)
    at com.android.microdroid.test.host.CommandRunner.run(CommandRunner.java:52)
    at com.android.virt.fs.AuthFsHostTest.testOutputDirectory_WriteToFdOfDeletedFile(AuthFsHostTest.java:461)

Bug: 280864756
Test: TH
Change-Id: I46636fac102e76cd60ff870e11a0e3d1a7af1077