Update needed for Rust v1.77.0
Bug: http://b/330185853

error: written amount is not handled
   --> packages/modules/Virtualization/zipfuse/src/main.rs:354:17
    |
354 |                 w.write(&buf[start..end])?
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: use `Write::write_all` instead, or handle partial writes
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
    = note: `#[deny(clippy::unused_io_amount)]` on by default

error: aborting due to 1 previous error


error: file opened with `create`, but `truncate` behavior not defined
   --> packages/modules/Virtualization/service_vm/manager/src/lib.rs:227:10
    |
227 |         .create(true)
    |          ^^^^^^^^^^^^- help: add: `.truncate(true)`
    |
    = help: if you intend to overwrite an existing file entirely, call `.truncate(true)`
    = help: if you instead know that you may want to keep some parts of the old file, call `.truncate(false)`
    = help: alternatively, use `.append(true)` to append to the file instead of overwriting it
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_open_options
    = note: `-D clippy::suspicious-open-options` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::suspicious_open_options)]`

error: aborting due to 1 previous error

01:22:40 ninja failed with: exit status 1


error: field `0` is never read
  --> packages/modules/Virtualization/vm/src/main.rs:37:15
   |
37 | struct Idsigs(Vec<PathBuf>);
   |        ------ ^^^^^^^^^^^^
   |        |
   |        field in this struct
   |
   = note: `Idsigs` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(dead_code)]`
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
   |
37 | struct Idsigs(());


Test: ./test_compiler.py --prebuilt-path dist/rust-dev.tar.xz  --target aosp_cf_x86_64_phone --image
Change-Id: I22a1ad28f26c99e7e766e677b4cf13bc340bf95d